-- FIRST
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM Worker;

-- SECOND
INSERT INTO Bonus(WORKER_REF_ID, BONUS_DATE, BONUS_AMOUNT) VALUES (3, '2020-01-01 01:01:01', 10000);

-- THIRD
SELECT
Worker.WORKER_ID,
(SELECT SUM(BONUS_AMOUNT) FROM Bonus WHERE Bonus.WORKER_REF_ID = Worker.WORKER_ID) as TOTAL_AMOUNT
FROM Worker;

-- FOURTH
SELECT DISTINCT
Title.WORKER_TITLE,
COUNT(Title.WORKER_TITLE) as COUNT_WORKERS
FROM Title
GROUP BY Title.WORKER_TITLE;